### ISSUE TITLE
Parser doesn't handle map/list/set consts

### ISSUE THREAD

**Issue by cespare** [samuel/go-thrift#13]
Example:

```
const map<string,string> M1 = {"hello": "world", "goodnight": "moon"}
```

The parser chokes when it gets to the `{`.

I would expect this to yield the following Go, I think:

``` go
var M1 = map[string]string{"hello": "world", "goodnight": "moon"}
```

I'm currently working on fixing this, but any pointers you could give would be great.

**Comment by samuel** [comment]
Fixed in https://github.com/samuel/go-thrift/commit/214000146059b2438ee094c68ec17b3828a8a43d
