### ISSUE TITLE
can not parse when idl file contains include word

### ISSUE THREAD

**Issue by cloudaice** [samuel/go-thrift#35]
When I generate a idl file, this file contains `include` word, then generation is failed, output is like this:

    <reader>:1:1 (0): no match found

**Comment by samuel** [comment]
Oops, sorry about that. I broke that in the replacing of the parser.

Pushed a fix to master. Let me know if it works for you. https://github.com/samuel/go-thrift/commit/8588238f34849814a63da04d311ca41c845b69b9

**Comment by cloudaice** [comment]
It works now, thank you very much.
