### ISSUE TITLE
namespace can not contains digit letter.

### ISSUE THREAD

**Issue by cloudaice** [samuel/go-thrift#37]
If namespace contains digit letter. generate will throw error. I find the regular expression about namespace is  `ns:[a-zA-z.]+`  in grammar.peg file. Should we change it to `ns:[a-z0-9A-z.]+`? Do you think the namespace word contains digit letter is normal.

**Comment by cloudaice** [comment]
Why not use `Identifier` instead of `[a-zA-z.]+`, like `ns:Identifier`, The thrift idl [spec](https://thrift.apache.org/docs/idl) also use `Identifier`.

**Comment by samuel** [comment]
Good call. Thanks for reporting this.
