### ISSUE TITLE
Compatible with the official generated codes?

### ISSUE THREAD

**Issue by zhaojkun** [samuel/go-thrift#38]
I have writen some service using the code generated by apache official tool,then use go-thrift in the client,but the client failed to call the service.Is it compatible with codes generated by the official tool ?

**Comment by samuel** [comment]
The serialization and RPC protocol are fully compatible, but the generated code and package interface are not. I took a different road with this package trying to make it smaller and nicer to use by being more natural Go. This package includes a generator though that you can use to create compatible structs and RPC interfaces if you like.

If you're having difficulties with communications between client and server the cause I've most often seen is difference in either using a framing or non-framing transport.

**Comment by zhaojkun** [comment]
Thank you.I have used the non-framing transport and the commutation is ok .
But in the my project.The number of one struct fields is 103 , larger than 64.So I think using a bitset struct in  structMeta more than uint64 may be better.

**Comment by samuel** [comment]
I opened up a separate issue to track the issue with ID >= 64: https://github.com/samuel/go-thrift/issues/62
