### ISSUE TITLE
Support 'union' structs

### ISSUE THREAD

**Issue by ximyu** [samuel/go-thrift#45]
Currently when I try to parse a Thrift file using union, I'll get the following error messages:
```
2015/08/17 10:37:41 Could not parse .thrift file: <reader>:164:1 (3915): rule SyntaxError: parser: syntax error
```

By some search, below is a real world example Thrift file using `union` quite a lot.  Would be nice to also add this to test files.
https://github.com/apache/aurora/blob/master/api/src/main/thrift/org/apache/aurora/gen/api.thrift

**Comment by samuel** [comment]
Parsing is straightforward.. the trick will be how to represent it in Go (e.g. as an `interface{}` or synthesize a struct with multiple fields of concrete types or ...)

**Comment by ximyu** [comment]
I think the Apache Thrift one will represent `union` as a Golang struct.

Thrift:
```thrift
union Query {
  1: string id
  2: string name
}
```

Generated Go:
```go
type Query struct {
	Id       string   `thrift:"id,1" json:"id"`
	Name string `thrift:"name,2" json:"name"`
}
```

**Comment by samuel** [comment]
Ahh, good to know. Probably best to do the same.
